### ISSUE TITLE
What to do after generate .zip file

### ISSUE THREAD

**Issue by sredXNY** [SchumacherFM/wordpress-to-hugo-exporter#40]
Hi, am really confused about what to do after generates the .zip file, it was generated successfully. I have this directory structure:

- 22.2
     >index.md

- appointment-booking

- contact-form

- frontpage

- post

- wp-content

- config.yaml

What should I do then? I ran `hugo` but it says that content folder not found, so I changed the name of wp-content to content.
Also I ran hugo server, started to listen in :1313 port but nothing is showed there.

I am not clear on what to do after generate the .zip file essentially

**Comment by SchumacherFM** [comment]
Hey! Now it's getting complicated and I can't help you much because I don't know too much of your project.

One start would be that you create a structure with hugo that really works. Go to the hugo documentation and start from scratch. After the basic site with your preferred theme runs you can add the content of your blog. Try first with one page and once you figured out how it works you can add the rest.

http://gohugo.io/overview/quickstart/
