### ISSUE TITLE
how to export wordpress directory on the command line

### ISSUE THREAD

**Issue by maitra** [SchumacherFM/wordpress-to-hugo-exporter#79]
Hello, I am a bit unclear about how to use this on the commandline. I have downloaded a wordpress website directory (or whatever these things are called) to my local folder. How do I use the commandline on this folder? I am using linux. Thanks very much!

**Comment by Ildarik** [comment]
I had the same question and after researching internet find that:
1) you should download `wordpress-to-hugo-exporter-master.zip`
2) unzip it into `wp-content/plugins/` directory
3) inside that directory run `sudo php hugo-export-cli.php`

But unfortunately it requires locally installed wordpress :(

**Comment by end2endzone** [comment]
I am not certain on what the OP actually wanted. I will add my user case in the hope that it might help someone else. I also had to use the command line to execute the plugin (remotely). 

My user case: I installed the plugin on my remote wordpress install hosted on hostgator.com. The problem was the download zip file was "truncated". Not all my posts were included in the zip file. Only the first few post with their data files. I do not know why I had such an issue. It might be because my host have set execution time limits, memory limitations or something like that. Anyway.

The workaround was to run the plugin from the command line. The guide I used [is the following](https://ma.ttias.be/step-by-step-guide-migrating-wordpress-to-hugo/). It explain multiple ways to use this plugin to export your posts. Basicaly, I had to connect to my provider using ssh and then I had to execute the following on the command line to be able to download the zip file:
```
cd ~/public_html/wp-content/plugins/wordpress-to-hugo-exporter-master/
php hugo-export-cli.php
mv /tmp/wp-hugo.zip ~/public_html/
```

and then, I download the resulting 650mb zip file using the url https://www.mywebsite.com/wp-hugo.zip
(don't forget to delete file wp-hugo.zip after downloading)

**Comment by maitra** [comment]
Thanks, I see.

**Comment by SchumacherFM** [comment]
seems like it has been solved, so closing. I can reopen on request.

**Comment by maitra** [comment]
Actually, it appears that we need access to wordpress to run this export? I no longer have access to wordpress.
