### ISSUE TITLE
Timeout... I think?

### ISSUE THREAD

**Issue by wagslane** [SchumacherFM/wordpress-to-hugo-exporter#95]
I have a site with 200+ posts, has this been tested with sites that large?

I'm consistently getting a timeout, is there a way for me to work around that?

**Comment by SchumacherFM** [comment]
Hey, I have no idea how large sites are which are getting exported but I assume 200+ posts is not that much.
You will see more success if you can run this script on the command line of the server with adjusted parameter.
Or you download the WP database to your local computer and run it there.

**Comment by wagslane** [comment]
Turns out cloudflare times out at 100+ second requests... and it looks like I can't turn it off. Is there a reason it was decided to do a long-running  HTTP request instead of a download? I didn't have problems with "all In one WP exporter" for example

**Comment by Rumperuu** [comment]
I was having a similar issue (on shared hosting, so I had no ability to increase the timeout threshold or run the CLI command).

As a workaround, I temporarily renamed my `wp-content/uploads/` folder and ran the tool through the WordPress admin panel, which worked (as the issue was that the tool was trying to export all of my Media too).

**Comment by SchumacherFM** [comment]
closing this due to age. please reopen if the problem still exists.
